[package]
name = "octa-output"
description = "Structured output and rendering for Octa"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
include = ["src/"]

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
console = { workspace = true }
base64 = { workspace = true }
humanize-duration = "0.0.7"
indicatif = { workspace = true }
nu-ansi-term = "0.50.3"
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tera = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
indicatif = { workspace = true, features = ["in_memory"] }
