[package]
name = "octa-executor"
description = "Execute tasks"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
include = ["src/"]

[dependencies]
octa-octafile = { version = "0.3.0", path = "../octa-octafile" }
octa-dag = { version = "0.3.0", path = "../octa-dag" }
octa-finder = { version = "0.3.0", path = "../octa-finder" }
octa-plugin = { version = "0.3.0", path = "../octa-plugin" }
octa-plugin-manager = { version = "0.3.0", path = "../octa-plugin-manager" }
octa-output = { version = "0.3.0", path = "../octa-output" }
octa-cache = { version = "0.3.0", path = "../octa-cache" }
octa-cache-protocol = { version = "0.3.0", path = "../octa-cache-protocol" }
async-trait = { workspace = true }
blake3 = { workspace = true }
chrono = { version = "0.4.45", features = ["serde"] }
dunce = "1.0.5"
dotenvy = "0.15.7"
indexmap = { workspace = true }
lazy_static = { workspace = true }
futures = "0.3.34"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yml = { workspace = true }
shellexpand = "3.1.2"
whoami = { workspace = true }
tera = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tempfile = { workspace = true }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tracing-test = "0.2"
