[package]
name = "octa-cache-http"
description = "HTTP adapter for Octa's remote task-result cache"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
include = ["src/", "README.md"]

[dependencies]
async-trait = { workspace = true }
fastrand = { workspace = true }
futures = "0.3.34"
octa-cache = { version = "0.4.0", path = "../octa-cache" }
octa-cache-protocol = { version = "0.4.0", path = "../octa-cache-protocol" }
reqwest = { workspace = true }
same-file = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["io"] }
zeroize = { workspace = true }
tempfile = { workspace = true }
url = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
octa-cache-test-support = { path = "../octa-cache-test-support" }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
