[package]
name = "octa-plugin"
description = "Plugin common"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
include = ["src/"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
chrono = "0.4"
clap = { version = "4.6", features = ["derive"] }
ctrlc = "3.5.2"
interprocess = { git = "https://github.com/federico-terzi/interprocess", features = [
  "tokio",
] }
lazy_static = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = "3.27"
regex = "1.13"
