[package]
name = "octa-plugin-manager"
description = "Plugin common"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
include = ["src/"]

[dependencies]
async-trait = { workspace = true }
futures-util = "0.3.34"
interprocess = { git = "https://github.com/federico-terzi/interprocess", features = [
  "tokio",
] }
octa-plugin = { version = "0.3.0", path = "../octa-plugin" }
octa-plugin-lock = { version = "0.3.0", path = "../octa-plugin-lock" }
dunce = "1.0.5"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yml = { workspace = true }
sha2 = "0.11"
same-file = { workspace = true }
jsonschema = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full", "test-util"] }
tokio-util = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = "3.27"
