[package]
name = "octa_plugin_shell"
description = "Plugin for run shell commands"
version = "0.2.1"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
include = ["src/"]

[[bin]]
name = "octa_plugin_shell"
bench = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
brush-builtins = "0.2.0"
brush-core = "0.5.0"
brush-coreutils-builtins = { version = "0.1.0", features = [
  "coreutils.base64",
  "coreutils.cat",
  "coreutils.cp",
  "coreutils.ls",
  "coreutils.mkdir",
  "coreutils.mktemp",
  "coreutils.mv",
  "coreutils.rm",
  "coreutils.sleep",
  "coreutils.touch",
] }
octa-plugin = { version = "0.2.1", path = "../octa-plugin" }
futures-util = "0.3.34"
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.27"
tera = { workspace = true }
tokio = { workspace = true, features = ["full", "test-util"] }
tokio-util = { workspace = true }
[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_System_Threading"] }
[target.'cfg(unix)'.dependencies]
nix = "0.31"

[dev-dependencies]
octa-plugin-manager = { version = "0.2.1", path = "../octa-plugin-manager" }
